import Head from 'next/head'
import { Inter } from 'next/font/google'
import Header from '@/component/Header'
import Footer from '@/component/Footer'
import OneWayComponent from '@/component/OneWayComponent'
import RoundTripComponent from '@/component/RoundTripComponent'
import React from "react";




const inter = Inter({ subsets: ['latin'] })

export default function Home() {

  return (
    <>

      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <>
          {/* Header Area */}
          <Header />
          {/* search */}
          <div className="search-overlay">
            <div className="d-table">
              <div className="d-table-cell">
                <div className="search-overlay-layer" />
                <div className="search-overlay-layer" />
                <div className="search-overlay-layer" />
                <div className="search-overlay-close">
                  <span className="search-overlay-close-line" />
                  <span className="search-overlay-close-line" />
                </div>
                <div className="search-overlay-form">
                  <form>
                    <input
                      type="text"
                      className="input-search"
                      placeholder="Search here..."
                    />
                    <button type="button">
                      <i className="fas fa-search" />
                    </button>
                  </form>
                </div>
              </div>
            </div>
          </div>
          {/* Banner Area */}
          <section id="home_one_banner">
            <div className="container">
              <div className="row align-items-center">
                <div className="col-lg-12">
                  <div className="banner_one_text">
                    <h1>Explore the world together</h1>
                    <h3>Find awesome flights, hotel, tour, car and packages</h3>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* Form Area */}
          <section id="theme_search_form">
            <div className="container">
              <div className="row">
                <div className="col-lg-12">
                  <div className="theme_search_form_area">
                    <div className="theme_search_form_tabbtn">
                      <ul className="nav nav-tabs" role="tablist">
                        <li className="nav-item" role="presentation">
                          <button
                            className="nav-link active"
                            id="flights-tab"
                            data-bs-toggle="tab"
                            data-bs-target="#flights"
                            type="button"
                            role="tab"
                            aria-controls="flights"
                            aria-selected="true"
                          >
                            <i className="fas fa-plane-departure" />
                            Flights
                          </button>
                        </li>
                        {/* <li className="nav-item" role="presentation">
                  <button
                    className="nav-link"
                    id="tours-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#tours"
                    type="button"
                    role="tab"
                    aria-controls="tours"
                    aria-selected="false"
                  >
                    <i className="fas fa-globe" />
                    Tours
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link"
                    id="hotels-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#hotels"
                    type="button"
                    role="tab"
                    aria-controls="hotels"
                    aria-selected="false"
                  >
                    <i className="fas fa-hotel" />
                    Hotels
                  </button>
                </li>
                <li className="nav-item" role="presentation">
                  <button
                    className="nav-link"
                    id="visa-tab"
                    data-bs-toggle="tab"
                    data-bs-target="#visa-application"
                    type="button"
                    role="tab"
                    aria-controls="visa"
                    aria-selected="false"
                  >
                    <i className="fas fa-passport" /> Visa
                  </button>
                </li> */}
                      </ul>
                    </div>
                    <div className="tab-content" id="myTabContent">
                      <div
                        className="tab-pane fade show active"
                        id="flights"
                        role="tabpanel"
                        aria-labelledby="flights-tab"
                      >
                        <div className="row">
                          <div className="col-lg-12">
                            <div className="flight_categories_search">
                              <ul className="nav nav-tabs" role="tablist">
                                <li className="nav-item" role="presentation">
                                  <button
                                    className="nav-link active"
                                    id="oneway-tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#oneway_flight"
                                    type="button"
                                    role="tab"
                                    aria-controls="oneway_flight"
                                    aria-selected="true"
                                  >
                                    One Way
                                  </button>
                                </li>
                                <li className="nav-item" role="presentation">
                                  <button
                                    className="nav-link"
                                    id="roundtrip-tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#roundtrip"
                                    type="button"
                                    role="tab"
                                    aria-controls="roundtrip"
                                    aria-selected="false"
                                  >
                                    Roundtrip
                                  </button>
                                </li>
                                <li className="nav-item" role="presentation">
                                  <button
                                    className="nav-link"
                                    id="multi_city-tab"
                                    data-bs-toggle="tab"
                                    data-bs-target="#multi_city"
                                    type="button"
                                    role="tab"
                                    aria-controls="multi_city"
                                    aria-selected="false"
                                  >
                                    Multi city
                                  </button>
                                </li>
                              </ul>
                            </div>
                          </div>
                        </div>
                        <div className="tab-content" id="myTabContent1">
                          <div
                            className="tab-pane fade show active"
                            id="oneway_flight"
                            role="tabpanel"
                            aria-labelledby="oneway-tab"
                          >
                            <OneWayComponent />
                          </div>
                          <div
                            className="tab-pane fade"
                            id="roundtrip"
                            role="tabpanel"
                            aria-labelledby="roundtrip-tab"
                          >
                           <RoundTripComponent />
                          </div>
                          <div
                            className="tab-pane fade"
                            id="multi_city"
                            role="tabpanel"
                            aria-labelledby="multi_city-tab"
                          >
                            <div className="row">
                              <div className="col-lg-12">
                                <div className="oneway_search_form">
                                  <form action="#!">
                                    <div className="multi_city_form_wrapper">
                                      <div className="multi_city_form">
                                        <div className="row">
                                          <div className="col-lg-3 col-md-6 col-sm-12 col-12">
                                            <div className="flight_Search_boxed">
                                              <p>From</p>
                                              <input
                                                type="text"
                                                defaultValue="New York"
                                              />
                                              <span>
                                                DAC, Hazrat Shahajalal International...
                                              </span>
                                              <div className="plan_icon_posation">
                                                <i className="fas fa-plane-departure" />
                                              </div>
                                            </div>
                                          </div>
                                          <div className="col-lg-3 col-md-6 col-sm-12 col-12">
                                            <div className="flight_Search_boxed">
                                              <p>To</p>
                                              <input
                                                type="text"
                                                defaultValue="London "
                                              />
                                              <span>LCY, London city airport </span>
                                              <div className="plan_icon_posation">
                                                <i className="fas fa-plane-arrival" />
                                              </div>
                                              <div className="range_plan">
                                                <i className="fas fa-exchange-alt" />
                                              </div>
                                            </div>
                                          </div>
                                          <div className="col-lg-4 col-md-6 col-sm-12 col-12">
                                            <div className="form_search_date">
                                              <div className="flight_Search_boxed date_flex_area">
                                                <div className="Journey_date">
                                                  <p>Journey date</p>
                                                  <input
                                                    type="date"
                                                    defaultValue="2022-05-05"
                                                  />
                                                  <span>Thursday</span>
                                                </div>
                                                <div className="Journey_date">
                                                  <p>Return date</p>
                                                  <input
                                                    type="date"
                                                    defaultValue="2022-05-10"
                                                  />
                                                  <span>Saturday</span>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                          <div className="col-lg-2  col-md-6 col-sm-12 col-12">
                                            <div className="flight_Search_boxed dropdown_passenger_area">
                                              <p>Passenger, Class </p>
                                              <div className="dropdown">
                                                <button
                                                  className="dropdown-toggle final-count"
                                                  data-toggle="dropdown"
                                                  type="button"
                                                  id="dropdownMenuButton1"
                                                  data-bs-toggle="dropdown"
                                                  aria-expanded="false"
                                                >
                                                  0 Passenger
                                                </button>
                                                <div
                                                  className="dropdown-menu dropdown_passenger_info"
                                                  aria-labelledby="dropdownMenuButton1"
                                                >
                                                  <div className="traveller-calulate-persons">
                                                    <div className="passengers">
                                                      <h6>Passengers</h6>
                                                      <div className="passengers-types">
                                                        <div className="passengers-type">
                                                          <div className="text">
                                                            <span className="count pcount">
                                                              2
                                                            </span>
                                                            <div className="type-label">
                                                              <p>Adult</p>
                                                              <span>12+ yrs</span>
                                                            </div>
                                                          </div>
                                                          <div className="button-set">
                                                            <button
                                                              type="button"
                                                              className="btn-add"
                                                            >
                                                              <i className="fas fa-plus" />
                                                            </button>
                                                            <button
                                                              type="button"
                                                              className="btn-subtract"
                                                            >
                                                              <i className="fas fa-minus" />
                                                            </button>
                                                          </div>
                                                        </div>
                                                        <div className="passengers-type">
                                                          <div className="text">
                                                            <span className="count ccount">
                                                              0
                                                            </span>
                                                            <div className="type-label">
                                                              <p className="fz14 mb-xs-0">
                                                                Children
                                                              </p>
                                                              <span>
                                                                2 - Less than 12 yrs
                                                              </span>
                                                            </div>
                                                          </div>
                                                          <div className="button-set">
                                                            <button
                                                              type="button"
                                                              className="btn-add-c"
                                                            >
                                                              <i className="fas fa-plus" />
                                                            </button>
                                                            <button
                                                              type="button"
                                                              className="btn-subtract-c"
                                                            >
                                                              <i className="fas fa-minus" />
                                                            </button>
                                                          </div>
                                                        </div>
                                                        <div className="passengers-type">
                                                          <div className="text">
                                                            <span className="count incount">
                                                              0
                                                            </span>
                                                            <div className="type-label">
                                                              <p className="fz14 mb-xs-0">
                                                                Infant
                                                              </p>
                                                              <span>
                                                                Less than 2 yrs
                                                              </span>
                                                            </div>
                                                          </div>
                                                          <div className="button-set">
                                                            <button
                                                              type="button"
                                                              className="btn-add-in"
                                                            >
                                                              <i className="fas fa-plus" />
                                                            </button>
                                                            <button
                                                              type="button"
                                                              className="btn-subtract-in"
                                                            >
                                                              <i className="fas fa-minus" />
                                                            </button>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                    <div className="cabin-selection">
                                                      <h6>Cabin Class</h6>
                                                      <div className="cabin-list">
                                                        <button
                                                          type="button"
                                                          className="label-select-btn"
                                                        >
                                                          <span className="muiButton-label">
                                                            Economy
                                                          </span>
                                                        </button>
                                                        <button
                                                          type="button"
                                                          className="label-select-btn active"
                                                        >
                                                          <span className="muiButton-label">
                                                            Business
                                                          </span>
                                                        </button>
                                                        <button
                                                          type="button"
                                                          className="label-select-btn"
                                                        >
                                                          <span className="MuiButton-label">
                                                            First Class{" "}
                                                          </span>
                                                        </button>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                              <span>Business</span>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <div className="multi_city_form">
                                        <div className="row">
                                          <div className="col-lg-3 col-md-6 col-sm-12 col-12">
                                            <div className="flight_Search_boxed">
                                              <p>From</p>
                                              <input
                                                type="text"
                                                defaultValue="New York"
                                              />
                                              <span>
                                                DAC, Hazrat Shahajalal International...
                                              </span>
                                              <div className="plan_icon_posation">
                                                <i className="fas fa-plane-departure" />
                                              </div>
                                            </div>
                                          </div>
                                          <div className="col-lg-3 col-md-6 col-sm-12 col-12">
                                            <div className="flight_Search_boxed">
                                              <p>To</p>
                                              <input
                                                type="text"
                                                defaultValue="London "
                                              />
                                              <span>LCY, London city airport </span>
                                              <div className="plan_icon_posation">
                                                <i className="fas fa-plane-arrival" />
                                              </div>
                                              <div className="range_plan">
                                                <i className="fas fa-exchange-alt" />
                                              </div>
                                            </div>
                                          </div>
                                          <div className="col-lg-4 col-md-6 col-sm-12 col-12">
                                            <div className="form_search_date">
                                              <div className="flight_Search_boxed date_flex_area">
                                                <div className="Journey_date">
                                                  <p>Journey date</p>
                                                  <input
                                                    type="date"
                                                    defaultValue="2022-05-05"
                                                  />
                                                  <span>Thursday</span>
                                                </div>
                                                <div className="Journey_date">
                                                  <p>Return date</p>
                                                  <input
                                                    type="date"
                                                    defaultValue="2022-05-12"
                                                  />
                                                  <span>Saturday</span>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                          <div className="col-lg-2  col-md-6 col-sm-12 col-12">
                                            <div className="flight_Search_boxed dropdown_passenger_area">
                                              <p>Passenger, Class </p>
                                              <div className="dropdown">
                                                <button
                                                  className="dropdown-toggle final-count"
                                                  data-toggle="dropdown"
                                                  type="button"
                                                  id="dropdownMenuButton1"
                                                  data-bs-toggle="dropdown"
                                                  aria-expanded="false"
                                                >
                                                  0 Passenger
                                                </button>
                                                <div
                                                  className="dropdown-menu dropdown_passenger_info"
                                                  aria-labelledby="dropdownMenuButton1"
                                                >
                                                  <div className="traveller-calulate-persons">
                                                    <div className="passengers">
                                                      <h6>Passengers</h6>
                                                      <div className="passengers-types">
                                                        <div className="passengers-type">
                                                          <div className="text">
                                                            <span className="count pcount">
                                                              2
                                                            </span>
                                                            <div className="type-label">
                                                              <p>Adult</p>
                                                              <span>12+ yrs</span>
                                                            </div>
                                                          </div>
                                                          <div className="button-set">
                                                            <button
                                                              type="button"
                                                              className="btn-add"
                                                            >
                                                              <i className="fas fa-plus" />
                                                            </button>
                                                            <button
                                                              type="button"
                                                              className="btn-subtract"
                                                            >
                                                              <i className="fas fa-minus" />
                                                            </button>
                                                          </div>
                                                        </div>
                                                        <div className="passengers-type">
                                                          <div className="text">
                                                            <span className="count ccount">
                                                              0
                                                            </span>
                                                            <div className="type-label">
                                                              <p className="fz14 mb-xs-0">
                                                                Children
                                                              </p>
                                                              <span>
                                                                2 - Less than 12 yrs
                                                              </span>
                                                            </div>
                                                          </div>
                                                          <div className="button-set">
                                                            <button
                                                              type="button"
                                                              className="btn-add-c"
                                                            >
                                                              <i className="fas fa-plus" />
                                                            </button>
                                                            <button
                                                              type="button"
                                                              className="btn-subtract-c"
                                                            >
                                                              <i className="fas fa-minus" />
                                                            </button>
                                                          </div>
                                                        </div>
                                                        <div className="passengers-type">
                                                          <div className="text">
                                                            <span className="count incount">
                                                              0
                                                            </span>
                                                            <div className="type-label">
                                                              <p className="fz14 mb-xs-0">
                                                                Infant
                                                              </p>
                                                              <span>
                                                                Less than 2 yrs
                                                              </span>
                                                            </div>
                                                          </div>
                                                          <div className="button-set">
                                                            <button
                                                              type="button"
                                                              className="btn-add-in"
                                                            >
                                                              <i className="fas fa-plus" />
                                                            </button>
                                                            <button
                                                              type="button"
                                                              className="btn-subtract-in"
                                                            >
                                                              <i className="fas fa-minus" />
                                                            </button>
                                                          </div>
                                                        </div>
                                                      </div>
                                                    </div>
                                                    <div className="cabin-selection">
                                                      <h6>Cabin Class</h6>
                                                      <div className="cabin-list">
                                                        <button
                                                          type="button"
                                                          className="label-select-btn"
                                                        >
                                                          <span className="muiButton-label">
                                                            Economy
                                                          </span>
                                                        </button>
                                                        <button
                                                          type="button"
                                                          className="label-select-btn active"
                                                        >
                                                          <span className="muiButton-label">
                                                            Business
                                                          </span>
                                                        </button>
                                                        <button
                                                          type="button"
                                                          className="label-select-btn"
                                                        >
                                                          <span className="MuiButton-label">
                                                            First Class{" "}
                                                          </span>
                                                        </button>
                                                      </div>
                                                    </div>
                                                  </div>
                                                </div>
                                              </div>
                                              <span>Business</span>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                    </div>
                                    <div className="row">
                                      <div className="col-lg-12">
                                        <div className="add_multy_form">
                                          <button type="button" id="addMulticityRow">
                                            + Add another flight
                                          </button>
                                        </div>
                                      </div>
                                    </div>
                                    <div className="top_form_search_button">
                                      <button className="btn btn_theme btn_md">
                                        Search
                                      </button>
                                    </div>
                                  </form>
                                </div>
                              </div>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className="tab-pane fade"
                        id="tours"
                        role="tabpanel"
                        aria-labelledby="tours-tab"
                      >
                        <div className="row">
                          <div className="col-lg-12">
                            <div className="tour_search_form">
                              <form action="#!">
                                <div className="row">
                                  <div className="col-lg-6 col-md-12 col-sm-12 col-12">
                                    <div className="flight_Search_boxed">
                                      <p>Destination</p>
                                      <input
                                        type="text"
                                        placeholder="Where are you going?"
                                      />
                                      <span>Where are you going?</span>
                                    </div>
                                  </div>
                                  <div className="col-lg-4 col-md-6 col-sm-12 col-12">
                                    <div className="form_search_date">
                                      <div className="flight_Search_boxed date_flex_area">
                                        <div className="Journey_date">
                                          <p>Journey date</p>
                                          <input
                                            type="date"
                                            defaultValue="2022-05-03"
                                          />
                                          <span>Thursday</span>
                                        </div>
                                        <div className="Journey_date">
                                          <p>Return date</p>
                                          <input
                                            type="date"
                                            defaultValue="2022-05-05"
                                          />
                                          <span>Thursday</span>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  <div className="col-lg-2  col-md-6 col-sm-12 col-12">
                                    <div className="flight_Search_boxed dropdown_passenger_area">
                                      <p>Passenger, Class </p>
                                      <div className="dropdown">
                                        <button
                                          className="dropdown-toggle final-count"
                                          data-toggle="dropdown"
                                          type="button"
                                          id="dropdownMenuButton1"
                                          data-bs-toggle="dropdown"
                                          aria-expanded="false"
                                        >
                                          0 Passenger
                                        </button>
                                        <div
                                          className="dropdown-menu dropdown_passenger_info"
                                          aria-labelledby="dropdownMenuButton1"
                                        >
                                          <div className="traveller-calulate-persons">
                                            <div className="passengers">
                                              <h6>Passengers</h6>
                                              <div className="passengers-types">
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count pcount">
                                                      2
                                                    </span>
                                                    <div className="type-label">
                                                      <p>Adult</p>
                                                      <span>12+ yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count ccount">
                                                      0
                                                    </span>
                                                    <div className="type-label">
                                                      <p className="fz14 mb-xs-0">
                                                        Children
                                                      </p>
                                                      <span>2 - Less than 12 yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add-c"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract-c"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count incount">
                                                      0
                                                    </span>
                                                    <div className="type-label">
                                                      <p className="fz14 mb-xs-0">
                                                        Infant
                                                      </p>
                                                      <span>Less than 2 yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add-in"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract-in"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                            <div className="cabin-selection">
                                              <h6>Cabin Class</h6>
                                              <div className="cabin-list">
                                                <button
                                                  type="button"
                                                  className="label-select-btn"
                                                >
                                                  <span className="muiButton-label">
                                                    Economy
                                                  </span>
                                                </button>
                                                <button
                                                  type="button"
                                                  className="label-select-btn active"
                                                >
                                                  <span className="muiButton-label">
                                                    Business
                                                  </span>
                                                </button>
                                                <button
                                                  type="button"
                                                  className="label-select-btn"
                                                >
                                                  <span className="MuiButton-label">
                                                    First Class{" "}
                                                  </span>
                                                </button>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <span>Business</span>
                                    </div>
                                  </div>
                                  <div className="top_form_search_button">
                                    <button className="btn btn_theme btn_md">
                                      Search
                                    </button>
                                  </div>
                                </div>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className="tab-pane fade"
                        id="hotels"
                        role="tabpanel"
                        aria-labelledby="hotels-tab"
                      >
                        <div className="row">
                          <div className="col-lg-12">
                            <div className="tour_search_form">
                              <form action="#!">
                                <div className="row">
                                  <div className="col-lg-6 col-md-12 col-sm-12 col-12">
                                    <div className="flight_Search_boxed">
                                      <p>Destination</p>
                                      <input
                                        type="text"
                                        placeholder="Where are you going?"
                                      />
                                      <span>Where are you going?</span>
                                    </div>
                                  </div>
                                  <div className="col-lg-4 col-md-6 col-sm-12 col-12">
                                    <div className="form_search_date">
                                      <div className="flight_Search_boxed date_flex_area">
                                        <div className="Journey_date">
                                          <p>Journey date</p>
                                          <input
                                            type="date"
                                            defaultValue="2022-05-03"
                                          />
                                          <span>Thursday</span>
                                        </div>
                                        <div className="Journey_date">
                                          <p>Return date</p>
                                          <input
                                            type="date"
                                            defaultValue="2022-05-05"
                                          />
                                          <span>Thursday</span>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  <div className="col-lg-2  col-md-6 col-sm-12 col-12">
                                    <div className="flight_Search_boxed dropdown_passenger_area">
                                      <p>Passenger, Class </p>
                                      <div className="dropdown">
                                        <button
                                          className="dropdown-toggle final-count"
                                          data-toggle="dropdown"
                                          type="button"
                                          id="dropdownMenuButton1"
                                          data-bs-toggle="dropdown"
                                          aria-expanded="false"
                                        >
                                          0 Passenger
                                        </button>
                                        <div
                                          className="dropdown-menu dropdown_passenger_info"
                                          aria-labelledby="dropdownMenuButton1"
                                        >
                                          <div className="traveller-calulate-persons">
                                            <div className="passengers">
                                              <h6>Passengers</h6>
                                              <div className="passengers-types">
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count pcount">
                                                      2
                                                    </span>
                                                    <div className="type-label">
                                                      <p>Adult</p>
                                                      <span>12+ yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count ccount">
                                                      0
                                                    </span>
                                                    <div className="type-label">
                                                      <p className="fz14 mb-xs-0">
                                                        Children
                                                      </p>
                                                      <span>2 - Less than 12 yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add-c"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract-c"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count incount">
                                                      0
                                                    </span>
                                                    <div className="type-label">
                                                      <p className="fz14 mb-xs-0">
                                                        Infant
                                                      </p>
                                                      <span>Less than 2 yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add-in"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract-in"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                            <div className="cabin-selection">
                                              <h6>Cabin Class</h6>
                                              <div className="cabin-list">
                                                <button
                                                  type="button"
                                                  className="label-select-btn"
                                                >
                                                  <span className="muiButton-label">
                                                    Economy
                                                  </span>
                                                </button>
                                                <button
                                                  type="button"
                                                  className="label-select-btn active"
                                                >
                                                  <span className="muiButton-label">
                                                    Business
                                                  </span>
                                                </button>
                                                <button
                                                  type="button"
                                                  className="label-select-btn"
                                                >
                                                  <span className="MuiButton-label">
                                                    First Class{" "}
                                                  </span>
                                                </button>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <span>Business</span>
                                    </div>
                                  </div>
                                  <div className="top_form_search_button">
                                    <button className="btn btn_theme btn_md">
                                      Search
                                    </button>
                                  </div>
                                </div>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                      <div
                        className="tab-pane fade"
                        id="visa-application"
                        role="tabpanel"
                        aria-labelledby="visa-tab"
                      >
                        <div className="row">
                          <div className="col-lg-12">
                            <div className="tour_search_form">
                              <form action="#!">
                                <div className="row">
                                  <div className="col-lg-3 col-md-12 col-sm-12 col-12">
                                    <div className="flight_Search_boxed">
                                      <p>Select country</p>
                                      <input type="text" defaultValue="United states" />
                                      <span>Where are you going?</span>
                                    </div>
                                  </div>
                                  <div className="col-lg-3 col-md-12 col-sm-12 col-12">
                                    <div className="flight_Search_boxed">
                                      <p>Your nationality</p>
                                      <input type="text" defaultValue="Bangladesh" />
                                      <span>Where are you going?</span>
                                    </div>
                                  </div>
                                  <div className="col-lg-4 col-md-6 col-sm-12 col-12">
                                    <div className="form_search_date">
                                      <div className="flight_Search_boxed date_flex_area">
                                        <div className="Journey_date">
                                          <p>Entry date</p>
                                          <input
                                            type="date"
                                            defaultValue="2022-05-03"
                                          />
                                          <span>Thursday</span>
                                        </div>
                                        <div className="Journey_date">
                                          <p>Exit date</p>
                                          <input
                                            type="date"
                                            defaultValue="2022-05-05"
                                          />
                                          <span>Thursday</span>
                                        </div>
                                      </div>
                                    </div>
                                  </div>
                                  <div className="col-lg-2  col-md-6 col-sm-12 col-12">
                                    <div className="flight_Search_boxed dropdown_passenger_area">
                                      <p>Traveller, Class </p>
                                      <div className="dropdown">
                                        <button
                                          className="dropdown-toggle final-count"
                                          data-toggle="dropdown"
                                          type="button"
                                          id="dropdownMenuButton1"
                                          data-bs-toggle="dropdown"
                                          aria-expanded="false"
                                        >
                                          0 Traveller
                                        </button>
                                        <div
                                          className="dropdown-menu dropdown_passenger_info"
                                          aria-labelledby="dropdownMenuButton1"
                                        >
                                          <div className="traveller-calulate-persons">
                                            <div className="passengers">
                                              <h6>Traveller</h6>
                                              <div className="passengers-types">
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count pcount">
                                                      2
                                                    </span>
                                                    <div className="type-label">
                                                      <p>Adult</p>
                                                      <span>12+ yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count ccount">
                                                      0
                                                    </span>
                                                    <div className="type-label">
                                                      <p className="fz14 mb-xs-0">
                                                        Children
                                                      </p>
                                                      <span>2 - Less than 12 yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add-c"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract-c"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                                <div className="passengers-type">
                                                  <div className="text">
                                                    <span className="count incount">
                                                      0
                                                    </span>
                                                    <div className="type-label">
                                                      <p className="fz14 mb-xs-0">
                                                        Infant
                                                      </p>
                                                      <span>Less than 2 yrs</span>
                                                    </div>
                                                  </div>
                                                  <div className="button-set">
                                                    <button
                                                      type="button"
                                                      className="btn-add-in"
                                                    >
                                                      <i className="fas fa-plus" />
                                                    </button>
                                                    <button
                                                      type="button"
                                                      className="btn-subtract-in"
                                                    >
                                                      <i className="fas fa-minus" />
                                                    </button>
                                                  </div>
                                                </div>
                                              </div>
                                            </div>
                                          </div>
                                        </div>
                                      </div>
                                      <span>Business</span>
                                    </div>
                                  </div>
                                  <div className="top_form_search_button">
                                    <button className="btn btn_theme btn_md">
                                      Search
                                    </button>
                                  </div>
                                </div>
                              </form>
                            </div>
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* imagination Area */}
          <section id="go_beyond_area" className="section_padding_top">
            <div className="container">
              <div className="row align-items-center">
                <div className="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div className="heading_left_area">
                    <h2>
                      Go beyond your <span>imagination</span>
                    </h2>
                    <h5>Discover your ideal experience with us</h5>
                  </div>
                </div>
                <div className="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div className="imagination_boxed">
                    <a href="top-destinations.html">
                      <img src="assets/img/imagination/imagination1.png" alt="img" />
                    </a>
                    <h3>
                      <a href="top-destinations.html">
                        7% Discount for all <span>Airlines</span>
                      </a>
                    </h3>
                  </div>
                </div>
                <div className="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div className="imagination_boxed">
                    <a href="top-destinations.html">
                      <img src="assets/img/imagination/imagination2.png" alt="img" />
                    </a>
                    <h3>
                      <a href="#!">
                        Travel around<span>the world</span>
                      </a>
                    </h3>
                  </div>
                </div>
                <div className="col-lg-3 col-md-6 col-sm-6 col-12">
                  <div className="imagination_boxed">
                    <a href="top-destinations.html">
                      <img src="assets/img/imagination/imagination3.png" alt="img" />
                    </a>
                    <h3>
                      <a href="top-destinations.html">
                        Luxury resorts<span>top deals</span>
                      </a>
                    </h3>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* Top destinations */}
          <section id="top_destinations" className="section_padding_top">
            <div className="container">
              {/* Section Heading */}
              <div className="row">
                <div className="col-lg-12 col-md-12 col-sm-12 col-12">
                  <div className="section_heading_center">
                    <h2>Top destinations</h2>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-lg-6 col-md-12 col-sm-12 col-12">
                  <div className="destinations_content_box img_animation">
                    <img src="assets/img/destination/big-img.png" alt="img" />
                    <div className="destinations_content_inner">
                      <h2>Up to</h2>
                      <div className="destinations_big_offer">
                        <h1>50</h1>
                        <h6>
                          <span>%</span> <span>Off</span>
                        </h6>
                      </div>
                      <h2>Holiday packages</h2>
                      <a href="top-destinations.html" className="btn btn_theme btn_md">
                        Book now
                      </a>
                    </div>
                  </div>
                </div>
                <div className="col-lg-6 col-md-12 col-sm-12 col-12">
                  <div className="row">
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination1.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">China</a>
                          </h3>
                        </div>
                      </div>
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination2.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">Darjeeling</a>
                          </h3>
                        </div>
                      </div>
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination3.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">Malaysia</a>
                          </h3>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination4.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">Gangtok</a>
                          </h3>
                        </div>
                      </div>
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination5.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">Thailand</a>
                          </h3>
                        </div>
                      </div>
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination6.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">Australia</a>
                          </h3>
                        </div>
                      </div>
                    </div>
                    <div className="col-lg-4 col-md-4 col-sm-12 col-12">
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination7.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">London</a>
                          </h3>
                        </div>
                      </div>
                      <div className="destinations_content_box img_animation">
                        <a href="top-destinations.html">
                          <img
                            src="assets/img/destination/destination8.png"
                            alt="img"
                          />
                        </a>
                        <div className="destinations_content_inner">
                          <h3>
                            <a href="top-destinations.html">USA</a>
                          </h3>
                        </div>
                      </div>
                      <div className="destinations_content_box">
                        <a
                          href="top-destinations.html"
                          className="btn btn_theme btn_md w-100"
                        >
                          View all
                        </a>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* Offer Area */}
          <section id="offer_area" className="section_padding_top">
            <div className="container">
              <div className="row">
                <div className="col-lg-6 col-md-12 col-sm-12 col-12">
                  <div className="offer_area_box d-none-phone img_animation">
                    <img src="assets/img/offer/offer1.png" alt="img" />
                    <div className="offer_area_content">
                      <h2>Special Offers</h2>
                      <p>
                        Invidunt ut labore et dolore magna aliquyam erat, sed diam
                        voluptua. At vero eos et accusam et justo duo dolores et ea
                        rebum. Stet clita kasd dolor sit amet. Lorem ipsum dolor sit
                        amet.
                      </p>
                      <a href="#!" className="btn btn_theme btn_md">
                        Holiday deals
                      </a>
                    </div>
                  </div>
                </div>
                <div className="col-lg-3 col-md-6 col-sm-12 col-12">
                  <div className="offer_area_box img_animation">
                    <img src="assets/img/offer/offer2.png" alt="img" />
                    <div className="offer_area_content">
                      <h2>News letter</h2>
                      <p>
                        Invidunt ut labore et dolore magna aliquyam erat, sed diam
                        voluptua. At vero eos et.
                      </p>
                      <a href="#!" className="btn btn_theme btn_md">
                        Subscribe now
                      </a>
                    </div>
                  </div>
                </div>
                <div className="col-lg-3 col-md-6 col-sm-12 col-12">
                  <div className="offer_area_box img_animation">
                    <img src="assets/img/offer/offer3.png" alt="img" />
                    <div className="offer_area_content">
                      <h2>Travel tips</h2>
                      <p>
                        Invidunt ut labore et dolore magna aliquyam erat, sed diam
                        voluptua. At vero eos et.
                      </p>
                      <a href="#!" className="btn btn_theme btn_md">
                        Get tips
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* Our partners Area */}
          <section id="our_partners" className="section_padding">
            <div className="container">
              {/* Section Heading */}
              <div className="row">
                <div className="col-lg-12 col-md-12 col-sm-12 col-12">
                  <div className="section_heading_center">
                    <h2>Our partners</h2>
                  </div>
                </div>
              </div>
              <div className="row">
                <div className="col-lg-12">
                  <div className="partner_slider_area owl-theme owl-carousel">
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/1.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/2.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/3.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/4.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/5.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/6.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/7.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/8.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/5.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/3.png" alt="logo" />
                      </a>
                    </div>
                    <div className="partner_logo">
                      <a href="#!">
                        <img src="assets/img/partner/2.png" alt="logo" />
                      </a>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </section>
          {/* Cta Area */}
          <section id="cta_area">
            <div className="container">
              <div className="row align-items-center">
                <div className="col-lg-7">
                  <div className="cta_left">
                    <div className="cta_icon">
                      <img src="assets/img/common/email.png" alt="icon" />
                    </div>
                    <div className="cta_content">
                      <h4>Get the latest news and offers</h4>
                      <h2>Subscribe to our newsletter</h2>
                    </div>
                  </div>
                </div>
                <div className="col-lg-5">
                  <div className="cat_form">
                    <form id="cta_form_wrappper">
                      <div className="input-group">
                        <input
                          type="text"
                          className="form-control"
                          placeholder="Enter your mail address"
                        />
                        <button className="btn btn_theme btn_md" type="button">
                          Subscribe
                        </button>
                      </div>
                    </form>
                  </div>
                </div>
              </div>
            </div>
          </section>
          <Footer />
        </>

      </main>
    </>
  )
}
